version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - redis
    ports:
      - "3000:3000"

  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_volume_data:
