version: '1.0'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  app:
    build:
      dockerfile: AppDockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./src:/app/src
    command: bash -c "npm run start"

volumes:
  pg-data:
  mongo-data:
  redis-data: